### ISSUE TITLE
Using helmet.xssFilter slows down our performance 3x

### ISSUE THREAD

**Issue by vsacheti** [helmetjs/x-xss-protection#1]
I work for yahoo, and we were doing performance evaluation of our stack and we found that 
using helmet.xssFilter slows down our performance by 3x.

On looking at it closely, its doing platform.parse on User-Agent header which looks like extremely complicated and expensive function.
Which basically it doesn't need, as it only needs to find IE, which I guess can be solved using a regex. 

Also even if  options.setOnOldIE is true, it still does platform.parse which is not needed strictly.

**Comment by EvanHahn** [comment]
Just pushed some changes to master that aren't yet on npm. The changes are:

1. Remove `platform.parse` and do things with a regular expression
2. If `setOnOldIE` is true, it does _no_ user-agent sniffing

The regular expression is faster than Platform, but still a bit slow.

What do you think of those changes?

**Comment by evantorrie** [comment]
Looks good.

I see a 3x speedup in our simple Hello World connect-based application.

From 2350 req/s to 7100+ req/s on my desktop after removing the dependency on `platform`

**Comment by EvanHahn** [comment]
I'll push a new version of this middleware and Helmet soon.

**Comment by EvanHahn** [comment]
Just published x-xss-protection@0.1.2 and helmet@0.6.2 with these performance updates.

**Comment by vsacheti** [comment]
Thanks Evan for the quick fix. I still see helmet 0.6.1 on the npm site.

**Comment by EvanHahn** [comment]
Whoops--fixed!
